Compute recovery rate
JinraeKim/FTCTests.jl pull request #5
Opened 2021-12-16 07:18 UTC by hnlee77

Resolve #3.
trajectory 정보가 담긴 .jld2 파일을 읽고, 고도 오차를 추출하도록 하는 함수를 완성하였습니다.
한가지 논의할 사항이 있는데, 오차 계산을 위해서 고도 참조값이 필요한데 (즉, command trajectory 정보) 이것을 데이터 저장할 때 함께 저장하여 불러오도록 하면 어떨까요? 혹은 계산된 오차값만을 저장하는 것도 괜찮을 것 같습니다.

2021-12-16 07:24 UTC, JinraeKim requested changes

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +using UnPack
Remove them

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +# using DifferentialEquations
Remove them

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +function export_errors(dir_log)
Receive "file path" or dir_log + file name

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +    file_path = joinpath(dir_log, "traj.jld2")
traj.jld2 이런거는 privileged name 을 정해도 좋겠네요

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +    pos_cmd_func = Bezier(θs; tf=tf)
\thetas, tf 를 저장하도록 해서 불러오게 해야할듯

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +end
Move it to e.g. `test/evaluation.jl`

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +# end
Remove them

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +    z_error_max = maximum(z_error)
마지막 5초만 잡기로 한 것 아닌가요?
몇초부터 마지막까지 잡을지 변수로 받게 하면 좋을듯 (namely, `t1`)
그럼 `t1 > tf` 인 경우 error 를 뱉어야겠죠?

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +    z_error = zs - zs_des
원래 고도오차만 가지고 회복률을 구하나요?

2021-12-16 07:24 UTC, JinraeKim commented on src/evaluate.jl
> +    z_error_max = maximum(z_error)
오차에 절대값도 취해야겠죠?

2021-12-16 07:25 UTC, hnlee77 commented on src/evaluate.jl
> +# using DifferentialEquations
주석은 일단 무시하기로 함

2021-12-16 07:30 UTC, hnlee77 commented on src/evaluate.jl
> +    file_path = joinpath(dir_log, "traj.jld2")
privileged name을 정한다는 것이 무슨 말인가요?

2021-12-16 07:30 UTC, hnlee77 commented on src/evaluate.jl
> +    pos_cmd_func = Bezier(θs; tf=tf)
요거는 `run_sim.jl` 파일 수정이 필요하겠어요.

2021-12-16 07:33 UTC, hnlee77 commented on src/evaluate.jl
> +end
OK.

2021-12-16 07:35 UTC, hnlee77 commented on src/evaluate.jl
> +    z_error = zs - zs_des
네 그랬죠?..

2021-12-16 07:39 UTC, JinraeKim commented on src/evaluate.jl
> +    z_error = zs - zs_des
![Uploading image.png…]()
위치오차로 보이네요

2021-12-16 07:42 UTC, hnlee77 commented on src/evaluate.jl
> +    z_error_max = maximum(z_error)
`filter`를 활용하기로 함.

2021-12-16 07:42 UTC, hnlee77 commented on src/evaluate.jl
> +    z_error = zs - zs_des
아니고 위치오차군요.

2021-12-16 08:16 UTC, JinraeKim commented on src/evaluate.jl
> +    pos_cmd_func = Bezier(θs; tf=tf)
#6 참고

2021-12-16 08:18 UTC, JinraeKim commented on src/evaluate.jl
> +    file_path = joinpath(dir_log, "traj.jld2")
#7 의 설명을 참고해주세요

2021-12-18 10:13 UTC, JinraeKim commented on src/evaluate.jl
> +    file_path = joinpath(dir_log, "traj.jld2")
일단 이에 대해서는 #7을 파두었으니 나중에 생각합시다 ㅎㅎ

2021-12-18 12:10 UTC, JinraeKim commented
리뷰를 희망하지 않고 작업중이면 draft 로 변경해주시는게 국룰이나,
우리끼리 하는 상황에서 draft 로 왔다갔다하기 번거로우니 리뷰를 희망한다는 코멘트를 남기는 식으로 하는게 좋겠습니다.

리뷰를 희망할 때마다 코멘트로 말씀 부탁드립니다~

2021-12-18 12:14 UTC, hnlee77 commented
일단 이전 코멘트들을 모두 반영했어요.
다음의 작업들을 진행할 예정입니다.
[] #9 머지 후 반영
[] #11 리뷰 후 반영하여 reference 를 이용한 error 계산 수정

2021-12-18 12:15 UTC, hnlee77 commented
> 리뷰를 희망하지 않고 작업중이면 draft 로 변경해주시는게 국룰이나, 우리끼리 하는 상황에서 draft 로 왔다갔다하기 번거로우니 리뷰를 희망한다는 코멘트를 남기는 식으로 하는게 좋겠습니다.
> 
> 리뷰를 희망할 때마다 코멘트로 말씀 부탁드립니다~

네

2021-12-18 12:25 UTC, hnlee77 commented
@JinraeKim #9 머지됨에 따라 rebase 진행해도 괜찮을까요?

2021-12-18 12:26 UTC, JinraeKim commented
> @JinraeKim #9 머지됨에 따라 rebase 진행해도 괜찮을까요?

그럼요!

2021-12-18 12:39 UTC, JinraeKim requested changes

2021-12-18 12:39 UTC, JinraeKim commented on src/evaluate.jl
> +function export_errors(file_path)
```suggestion
"""
t1: calculate maximum error from `t1` to `tf`
"""
function export_errors(file_path, t1::Real)
```

2021-12-18 12:39 UTC, JinraeKim commented on src/evaluate.jl
> +    filtered_df = filter(:time => t -> t > 15, df)
```suggestion
    filtered_df = filter(:time => t -> t >= t1, df)
```

2021-12-18 12:39 UTC, JinraeKim commented on src/evaluate.jl
> +    errors = sqrt.(xs.^2 + ys.^2 + zs.^2)
```suggestion
    poss = filtered_df.sol |> Map(datum -> datum.plant.state.p) |> collect
    # poss_des = ...
    # errors_pos = poss - poss_des |> Map(norm) |> collect  # you may need to `using LinearAlgebra`
    error("WIP")  # error message for not completed works
```

2021-12-18 12:39 UTC, JinraeKim commented on src/evaluate.jl
> +    @unpack df, method = loaded_data
```suggestion
    @unpack df, method, t0, tf = loaded_data
    @assert t1 < tf && t1 > t0
```

2021-12-18 12:39 UTC, JinraeKim commented on src/evaluate.jl
> +    ts = df.time
```suggestion
```

2021-12-18 12:39 UTC, JinraeKim commented on test/evaluation.jl
> +    file_path = joinpath(dir_log, "traj.jld2")
```suggestion
    file_path = joinpath(dir_log, FTCTests.TRAJ_DATA_NAME)
```

2021-12-18 12:44 UTC, JinraeKim commented on src/evaluate.jl
> +    errors = sqrt.(xs.^2 + ys.^2 + zs.^2)
아, `error` 를 위로 올리면 comment out 을 안해도 되는데 깜빡했군요 ㅎㅎ

2021-12-18 12:44 UTC, JinraeKim commented on src/evaluate.jl
> +function export_errors(file_path)
참고로 괜찮아보이는 (?) 가벼운 수정은 github 상에서 즉시 커밋할 수 있습니다~

2021-12-18 12:57 UTC, hnlee77 commented on src/evaluate.jl
> +    errors = sqrt.(xs.^2 + ys.^2 + zs.^2)
아래 내용이 실행되지 않는다는 것이죠?

2021-12-18 12:59 UTC, JinraeKim commented on src/evaluate.jl
> +    errors = sqrt.(xs.^2 + ys.^2 + zs.^2)
`error(msg)` 를 만나면 `msg` 를 출력하고 실행된 코드가 종료됩니다

2021-12-18 13:21 UTC, hnlee77 commented
#11 머지 후에 나머지 진행하도록 하겠습니다.

2021-12-18 14:05 UTC, hnlee77 commented
trajectory 정보가 담긴 하나의 jld2 파일을 읽어 회복률을 계산하였습니다.
다음으로 여러개의 jld2 파일을 읽어 회복률을 계산하도록 할 예정입니다.

2021-12-18 16:24 UTC, JinraeKim commented
Note: 각 기법 및 기동별로 100개씩의 데이터를 [구글드라이브](https://drive.google.com/drive/u/1/folders/14X5SkJKyU1RkhPUVnG206tPfxoZYQEKz) 에 업로드하였으니 여러 개 파일을 읽어 처리하는 경우에 받아쓰시면 될듯

2021-12-18 16:34 UTC, JinraeKim requested changes
무엇을 코드로 구현하려는지, 구현하려는 내용이 코드로 잘 구현되었는지 꼼꼼히 체크해주십셔 ㅎㅎ

2021-12-18 16:34 UTC, JinraeKim commented on src/evaluate.jl
> +end
```suggestion
"""
    evaluate(file_path, t1::Real, threshold::Real)

Evaluate whether the maximum error of trajectory data (loaded from `file_path`) does not exceed given `threshold` (check time period: `t1 < t < tf`).
"""
function evaluate(file_path, t1::Real, threshold::Real)
    @assert threshold > 0
    loaded_data = JLD2.load(file_path)
    @unpack df, method, t0, tf, traj_des = loaded_data
    @assert t1 < tf && t1 > t0
    filtered_df = filter(:time => t -> t >= t1, df)
    poss = filtered_df.sol |> Map(datum -> datum.plant.state.p) |> collect
    poss_des = filtered_df.time |> Map(traj_des) |> collect
    errors_pos = poss - poss_des |> Map(norm) |> collect
    maximum(errors_pos) <= threshold
end
```

보아하니 여러 개 중 뭐가 조건을 만족하는지의 비율을 따지는 것 같은데, 원래는 그냥 maximum 값이 threshold 를 넘으면 실패, 아니면 성공인거 아닌가요?
보고서 내용 참고 바랍니다.

2021-12-18 16:34 UTC, JinraeKim commented on test/evaluation.jl
> +    recovery_rate = 100 * FTCTests.evaluate(errors, threshold)
맞춰서 수정

2021-12-18 16:34 UTC, JinraeKim commented on src/evaluate.jl
> +end
![image](https://user-images.githubusercontent.com/43136096/146648600-866d7a95-85f3-43a7-9e23-b07058f23626.png)

2021-12-19 01:30 UTC, hnlee77 commented on src/evaluate.jl
> +end
음.. 여기에 바로 여러개의 trajectory에 따른 error들을 받아서 회복률을 계산하려고 헀었고, 현재는 한개의 error밖에 없어서 그렇습니다.

2021-12-19 01:33 UTC, hnlee77 commented on src/evaluate.jl
> +end
생각해보니 이것은 밖으로 빼서 따로 계산하는게 좋겠네요.

2021-12-19 01:34 UTC, hnlee77 commented on src/evaluate.jl
> +end
이미 작성한 내용이 있어서 일부만 가져다 쓰도록 하겠습니다 ㅎㅎ

2021-12-19 02:11 UTC, hnlee77 commented
처음에는 함수를 나누어 코드를 짜는게 좋을 것 같다고 생각해서 제 방식을 고수하였는데.. [이 내용](https://github.com/JinraeKim/FTCTests.jl/pull/5#pullrequestreview-835786267)을 다시 확인하면서 보니 이렇게 하나의 함수로 짜는게 훨씬 깔끔한 것 같다는 생각이 드네요..ㅎ 의견주세요 슨생님.
+ 추가로 시뮬레이션 횟수 `N`도 데이터로 저장하는건 어떨까요?

2021-12-19 02:14 UTC, hnlee77 commented on src/evaluate.jl
> +end
@JinraeKim 이건 별개의 얘기긴 한데 `df_filtered`와 같이 쓰는 것이 문법적으로 맞는 표현이라서 수정한 걸까요?..ㅎ

2021-12-19 02:19 UTC, JinraeKim commented on src/evaluate.jl
> +end
문법은 상관없고, 그 객체의 속성을 나타내는 것을 앞으로 빼는 것이 보통 가독성이 좋습니다.
예:
`df`: dataframe
`df_filtered`: dataframe, filtered
...

2021-12-19 02:20 UTC, JinraeKim commented
> 처음에는 함수를 나누어 코드를 짜는게 좋을 것 같다고 생각해서 제 방식을 고수하였는데.. [이 내용](https://github.com/JinraeKim/FTCTests.jl/pull/5#pullrequestreview-835786267)을 다시 확인하면서 보니 이렇게 하나의 함수로 짜는게 훨씬 깔끔한 것 같다는 생각이 드네요..ㅎ 의견주세요 슨생님.
> 
> * 추가로 시뮬레이션 횟수 `N`도 데이터로 저장하는건 어떨까요?

시뮬레이션 횟수는 데이터로 저장할 이유가 없습니다.
디렉토리로 이미 구분하고 있으니까요.

2021-12-19 02:37 UTC, JinraeKim commented
추가로, [이 코멘트](https://github.com/JinraeKim/FTCTests.jl/pull/5#discussion_r771842141) 에서 제가 의도한 것과, @hnlee77 가 의도하던 큰 그림이 달랐습니다.
현재 코드랑, 해당 코멘트의 코드가 같지 않습니다.

저라면
1-1) 한개의 파일을 읽어 성공/실패 여부를 계산하는 함수 작성 `evaluate(file_path::String)` (#3, #5)
1-2) 여러개의 파일을 읽어 성공/실패 여부를 계산하도록 확장 `evaluate(file_path::Vector{String})` (새 이슈 및 PR 파기)
2-1) 여러개의 파일을 읽어 0~1 사이로 회복률 계산 `calculate_recovery_rate(dir)`  (특정 디렉토리 내의 파일 또는 디렉토리명을 어레이로 받는 함수가 있습니다)
2-2 (필요할지 모르겠지만) 2-1) 로 긁어온 파일 중 앞에서 N 개까지만 사용하는 함수로 확장 `calculate_recovery_rate(dir; N=nothing)`

2-1 을 쓰다보니, 데이터 저장하는 구조를 읽어오는 입장에서 편하게 짜는게 좋겠다 싶네요.
이렇게 바꾸도록 할까요?

## 1안
1) 디렉토리: 기동으로 구분 (`hovering`, `forward`)
3) 디렉토리 내 파일: 각 시뮬레이션 케이스 및 기법에 대한 파일들 `$(method)_000$(N)_$(FTCTests.TRAJ_DATA_NAME)`

이러면 각 기동을 택하여 내부 파일을 싹 긁어오면 될 것 같아서요 (파일 내에 어떤 method 인지 저장되어있으니 회복률 계산 시 이에 맞추어 분류)

## 2안
1) 상위 디렉토리: 기동으로 구분 (`hovering`, `forward`)
2) 하위 디렉토리: 기법으로 구분 (`adaptive`, `adaptive2optim`)
3) 하위 디렉토리 내 파일: 각 시뮬레이션 케이스 및 기법에 대한 파일들 `$000$(N)_$(FTCTests.TRAJ_DATA_NAME)`

이거는 읽어오는 입장에서 좀 더 쉽긴 할 것 같습니다 (처음부터 기동/기법별로 구분이 되어있어서)

2021-12-19 03:06 UTC, hnlee77 commented
> 저라면 1-1) �한개의 파일을 읽어 성공/실패 여부를 계산하는 함수 작성 `evaluate(file_path::String)` (#3, #5) 1-2) 여러개의 파일을 읽어 성공/실패 여부를 계산하도록 확장 `evaluate(file_path::Vector{String})` (새 이슈 및 PR 파기) 2-1) 여러개의 파일을 읽어 0~1 사이로 회복률 계산 `calculate_recovery_rate(dir)` (특정 디렉토리 내의 파일 또는 디렉토리명을 어레이로 받는 함수가 있습니다) 2-2 (필요할지 모르겠지만) 2-1) 로 긁어온 파일 중 앞에서 N 개까지만 사용하는 함수로 확장 `calculate_recovery_rate(dir; N=nothing)` 로 진행할 것 같습니다.
> 
> 2-1 을 쓰다보니, 데이터 저장하는 구조를 읽어오는 입장에서 편하게 짜는게 좋겠다 싶네요. 이렇게 바꾸도록 할까요?
>

2안으로 수정하면 더 편하게 읽어올 수 있을 것 같습니다.

2021-12-19 03:07 UTC, JinraeKim commented
@hnlee77 해당 패치를 빠르게 진행해보겠습니다

2021-12-19 03:17 UTC, JinraeKim commented
> 1-1) �한개의 파일을 읽어 성공/실패 여부를 계산하는 함수 작성 `evaluate(file_path::String)` (#3, #5) 1-2) 여러개의 파일을 읽어 성공/실패 여부를 계산하도록 확장 `evaluate(file_path::Vector{String})` (새 이슈 및 PR 파기) 2-1) 여러개의 파일을 읽어 0~1 사이로 회복률 계산 `calculate_recovery_rate(dir)` (특정 디렉토리 내의 파일 또는 디렉토리명을 어레이로 받는 함수가 있습니다) 2-2 (필요할지 모르겠지만) 2-1) 로 긁어온 파일 중 앞에서 N 개까지만 사용하는 함수로 확장 `calculate_recovery_rate(dir; N=nothing)` 로 진행할 것 같습니다.
> 
> 2-1 을 쓰다보니, 데이터 저장하는 구조를 읽어오는 입장에서 편하게 짜는게 좋겠다 싶네요. 이렇게 바꾸도록 할까요?

아 물론, 고장 종류에 따라 회복률을 분류하는 것도 필요한 기능입니다.

2021-12-19 03:26 UTC, hnlee77 commented
> 
> 아 물론, 고장 종류에 따라 회복률을 분류하는 것도 필요한 기능입니다.

이건 추후 저장된 고장 인덱스에 따라 회복률을 분류하도록 해야될 것 같아요.

2021-12-19 03:26 UTC, JinraeKim commented
맞습니다 ㅎㅎ

2021-12-19 03:30 UTC, hnlee77 commented
딜레이도 있었군요 ㅎ..ㅋㅋㅋㅋㅋ

> 맞습니다 ㅎㅎ #4 에서 처리하시면 될듯~

그렇게 하겠습니다~

2021-12-19 07:26 UTC, hnlee77 commented
## 구성
파일의 구성내용은 다음과 같습니다.
1) 한개의 파일을 읽어 trajectory의 지정된 구간에서의 maximum error를 도출
2) 특정 디렉토리 내부에서 존재하는 파일의 수만큼 반환된 maximum error를 array 형태로 반환
3) 2)에서 반환된 errors를 이용해 회복률 계산

### 실행방법
``` julia
main(:manoeuvre, :method)
```
default 로는 manoeuvre=:hovering, method=:adaptive)입니다.

### 결과

현재 3개의 trajectory data를 이용하였고 REPL 결과는 다음과 같이 나옵니다.
``` julia
julia> main()
Recovery rate is: 100.0 percent.
(manoeuvre: hovering, method: adaptive)
```

2021-12-19 23:50 UTC, JinraeKim requested changes
readdir 함수를 사용하는게 좋겠습니다

2021-12-19 23:50 UTC, JinraeKim commented on test/evaluation.jl
> +function main(manoeuvre=:hovering, method=:adaptive)
```suggestion
"""
# Notes
- (`manoeuvre`) :hovering, :forward, etc.
- (`method`) :adaptive, :adaptive2optim, etc.
"""
function main(manoeuvre::Symbol=:hovering, method::Symbol=:adaptive; _dir_log="data")
    println("(manoeuvre: $(manoeuvre), method: $(method)")
```
`_dir_log` 는 기본인자로 들어가도 좋을듯?

2021-12-19 23:50 UTC, JinraeKim commented on test/evaluation.jl
> +    case_number = 1
```suggestion
```

2021-12-19 23:50 UTC, JinraeKim commented on test/evaluation.jl
> +    end
[readdir](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.readdir) 이라는 함수를 쓰는게 더 강건할 것 같습니다 (네이밍을 어떻게 하게 될지는 모르는것이기에...)

2021-12-19 23:50 UTC, JinraeKim commented on test/evaluation.jl
> +    println("(manoeuvre: ", manoeuvre, ", method: ", method, ")")
```suggestion
    println("Recovery rate is: $(recovery_rate) percent.")
```
Interpolation 을 쓰면 가독성이 더 좋습니다

2021-12-19 23:50 UTC, JinraeKim commented on test/evaluation.jl
> +    _dir_log = "data"
```suggestion
```

2021-12-20 02:56 UTC, JinraeKim commented
@hnlee77 제 제안은 다음과 같습니다:

지금 여러 개의 값을 읽어들여 바로 회복률을 계산하려고 합니다만, 그것보다는 하나의 파일을 읽어서
1-1) position error
1-2) position error 의 크기
2) 이에 따른 회복 성공 여부
를 뱉어주는게 좋겠습니다.

왜냐하면 #15 에서 어차피 여러 개의 파일을 읽어오는 것을 할 것이기에... 이 PR 에서 여러 개를 읽느라 어려워할 필요가 없어보이네요.

위의 값들을 출력하는 test 파일을 `test/evaluate.jl` 로 작성해주시면 좋겠습니다.

2021-12-20 04:56 UTC, hnlee77 commented on test/evaluation.jl
> +    end
OK.

2021-12-20 05:10 UTC, JinraeKim commented
#17 rebase 바람

2021-12-20 05:45 UTC, hnlee77 commented
수정사항 반영하여 하나의 trajectory에 대해 회복률 결과(성공 또는 실패)와 위치오차 최댓값을 내보내도록 하였습니다.

### 결과
```julia
(manoeuvre: hovering, method: adaptive)
Success.
```

2021-12-20 06:03 UTC, JinraeKim reviewed
리뷰를 하다보니 뭘 하려는지 모르겠어서...

회의 이후 잠시 볼 수 있을까요?

2021-12-20 06:03 UTC, JinraeKim commented on src/evaluate.jl
> +    return result, error_max, faults, fdi
```suggestion
    return result, error_max
```

왜 `faults` 랑 `fdi` 를 내보내죠?

2021-12-20 06:03 UTC, JinraeKim commented on src/evaluate.jl
> +end
```suggestion
```

2021-12-20 06:03 UTC, JinraeKim commented on src/evaluate.jl
> +end
더이상 필요가 없어보이네요

2021-12-20 06:03 UTC, JinraeKim commented on src/evaluate.jl
> +    @unpack df, method, faults, fdi, t0, tf, traj_des = data_loaded
```suggestion
    @unpack df, t0, tf, traj_des = data_loaded
```

2021-12-20 06:03 UTC, JinraeKim commented on Project.toml
> +Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
```suggestion
```

2021-12-20 06:08 UTC, JinraeKim commented on src/evaluate.jl
> +Evaluate whether the maximum error of trajectory data (loaded from `file_path`) does not exceed given `threshold` (check time period: `t1 < t < tf`) and export the maximum position error.
얘기하고 다시 리뷰

2021-12-20 06:09 UTC, hnlee77 commented on src/evaluate.jl
> +    return result, error_max, faults, fdi
추후 #15 에서 작성할 예정이라서 놔두었습니다.

2021-12-20 06:10 UTC, hnlee77 commented on src/evaluate.jl
> +end
이것도 추후 #15 에서 사용 예정입니다ㅠ

2021-12-20 06:10 UTC, hnlee77 commented on src/evaluate.jl
> +    @unpack df, method, faults, fdi, t0, tf, traj_des = data_loaded
마찬가지 입니다..ㅎ

2021-12-20 06:10 UTC, hnlee77 commented on Project.toml
> +Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
얘도.

2021-12-20 06:11 UTC, hnlee77 commented
> 리뷰를 하다보니 뭘 하려는지 모르겠어서...
> 
> 회의 이후 잠시 볼 수 있을까요?

추후 #15 에서 이어질 내용으로 놔둔 것이 대부분이긴 합니다만.. 그럽시다.

2021-12-20 06:39 UTC, JinraeKim commented
서로 다른 PR 의 의존성을 최대한 낮춰주세요.

예를 들어, 제 생각에는 지금 하려는 것은 한 녀석의 성공/실패 여부를 뱉어주면 되는거고 (기타 에러 등의 유용한 정보를 같이 뱉어줄수도 있긴 하죠)...
그냥 `export_error` 또는 `evaluate` 의 기능이 잘 작동하는지만 확인하는 테스트 코드가 있으면 되겠습니다.

혹시 줄리아에서 테스트 코드 작성 방법을 모르시면 답글 바랍니다.

2021-12-20 06:40 UTC, JinraeKim commented
아니면 제가 예시를 작성해보겠습니다

2021-12-20 06:42 UTC, hnlee77 commented
의존성을 낮춰 수정하도록 하겠습니다.

2021-12-20 06:52 UTC, hnlee77 commented
수정완료!

2021-12-20 07:03 UTC, JinraeKim commented
@hnlee77 
`compute-recovery-rate-jinrae-comment` 라는 브랜치를 봐주시겠어요?

2021-12-20 07:10 UTC, hnlee77 commented
내용이 아주 확 달라졌군요..

2021-12-20 07:11 UTC, JinraeKim commented
예시일 뿐이니 이따 같이 얘기해봅시다 ㅋㅋ

2021-12-20 10:35 UTC, JinraeKim commented
여기서부터 같이 작업함

2021-12-20 11:11 UTC, JinraeKim approved these changes

2021-12-20 12:08 UTC, merged